project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - index.qmd
  
execute:
  freeze: auto

website:
  title: "Scientific Computing Support"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/lter/scicomp
  repo-actions: [issue]
  twitter-card: true
  google-analytics: "G-YGFW2JT4EY"
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/lter/scicomp
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer: |
    <img src="images/lter_logo_square.png" width="40%"/>
    <img src="images/nceas_logo_square.png" width="40%"/>

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false
