project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Scientific Computing Support"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/NCEAS/scicomptasks
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home"
      - text: "Working Group Onboarding"
        menu: 
          - href: sci-comp-definition.qmd
            text: "What is Scientific Computing?"
          - onboard-scaffold_services.qmd
          - onboard-scaffold_infrastructure.qmd
          - onboard-scaffold_suggested-tools.qmd
          - onboard-scaffold_other-materials.qmd
      - text: "Trainings"
        menu:
         - workshops.qmd
         - tutorials.qmd
      - best_practices.qmd
      - portfolio.qmd
      - text: "Our Team"
        menu:
          - text: "People"
            href: staff.qmd
          - text: "Internal Onboarding"
            href: team-onboarding.qmd
    right:
      - icon: github
        href: https://github.com/NCEAS/scicomptasks
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer: |
    <img src="images/lter_logo_square.png" width="40%"/>
    <img src="images/nceas_logo_square.png" width="40%"/>

format:
  html:
    theme:
       light: yeti
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
